config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  # ------ TERMINAL ------ #
  billy_zshrc:
    dst: ~/.zshrc
    src: billy/.zshrc

  billy_p10k:
    dst: ~/.p10k.zsh
    src: billy/.p10k.zsh

  common_kitty:
    dst: ~/.config/kitty
    src: common/kitty

  # ------ SPOTIFY ------ #
  billy_spotifyd:
    dst: ~/.config/spotifyd
    src: billy/spotifyd

  billy_spotify_tui:
    dst: ~/snap/spt/current/.config/spotify-tui
    src: billy/spotify-tui

  billy_sptlrx:
    dst: ~/.config/sptlrx
    src: billy/sptlrx

  # ------ Hyprland and Such ------ #
  billy_hypr:
    dst: ~/.config/hypr
    src: billy/hypr
  
  billy_waybar:
    dst: ~/.config/waybar
    src: billy/waybar

  billy_rofi:
    dst: ~/.config/rofi
    src: billy/rofi

  bully_mako:
    dst: ~/.config/mako
    src: billy/mako

profiles:
  Billy:
    dotfiles:
      - common_kitty
      - billy_spotifyd
      - billy_spotify_tui
      - billy_zshrc
      - billy_p10k
      - billy_hypr
      - billy_waybar
      - billy_rofi
  Cthulu:
    dotfiles:
      - common_kitty
      - billy_zshrc
      - billy_p10k
