config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  # ------ TERMINAL ------ #
  billy_zshrc:
    dst: ~/.zshrc
    src: billy/.zshrc

  billy_p10k:
    dst: ~/.p10k.zsh
    src: billy/.p10k.zsh

  common_kitty:
    dst: ~/.config/kitty
    src: common/kitty

  # ------ Hyprland and Such ------ #
  billy_hypr:
    dst: ~/.config/hypr
    src: billy/hypr

  billy_waybar:
    dst: ~/.config/waybar
    src: billy/waybar

  billy_anyrun:
    dst: ~/.config/anyrun
    src: billy/anyrun

  billy_mako:
    dst: ~/.config/mako
    src: billy/mako

profiles:
  fedora:
    dotfiles:
      - common_kitty
      - billy_zshrc
      - billy_p10k
      - billy_hypr
      - billy_waybar
      - billy_anyrun
      - billy_mako
  Cthulu:
    dotfiles:
      - common_kitty
      - billy_zshrc
      - billy_p10k
