#!/bin/zsh

# ------ Start Wallpaper ------ #
swww-daemon --format xrgb &

# ------ Start Waybar ------ #
waybar -l trace >> /home/teo/.config/hypr/logs/waybar.log &

# ------ Network Manager Applet ------ #
nm-applet&

# ------ Start Authentication Agent ------ #
# Used when an application wants to elevate its privileges
exec /usr/lib/polkit-kde-authentication-agent-1
