#!/usr/bin/bash

wpDir="$HOME/Repos/Wallpapers/"

wpFile=$(find "$wpDir" -type f -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.gif" | shuf -n 1)

swww img $wpFile --transition-step 40 --transition-fps 60 --transition-type center
